fix: update logging

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -86,22 +86,25 @@ jobs:
 
           echo "Command ID: $command_id"
 
+          # Log each command's output and error for debugging
           for instance_id in "${INSTANCE_IDS_ARRAY[@]}"; do
             aws ssm wait command-executed \
               --command-id $command_id \
-              --instance-id $instance_id
-          done
-
-          commandOutput=$(aws ssm list-command-invocations --command-id $command_id --details)
-          echo "Command Output: $commandOutput"
-
-          # Log the output of each command executed on the EC2 instances
-          for instance_id in "${INSTANCE_IDS_ARRAY[@]}"; do
+              --instance-id $instance_id || true
+            
             invocation_output=$(aws ssm get-command-invocation --command-id $command_id --instance-id $instance_id --query "StandardOutputContent" --output text)
             echo "Standard Output for $instance_id: $invocation_output"
             invocation_error=$(aws ssm get-command-invocation --command-id $command_id --instance-id $instance_id --query "StandardErrorContent" --output text)
             echo "Standard Error for $instance_id: $invocation_error"
+
+            if [[ "$invocation_error" != "" ]]; then
+              echo "Command failed on instance $instance_id with error: $invocation_error"
+              exit 1
+            fi
           done
+
+          commandOutput=$(aws ssm list-command-invocations --command-id $command_id --details)
+          echo "Command Output: $commandOutput"
         env:
           AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
           AWS_REGION: ${{ secrets.AWS_REGION }}
